# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nodes',
            new_name='Node',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='nodes',
            new_name='node',
        ),
    ]
